/**
 * Pro API client — extracted into modules under pro-api/.
 * This file is now a backward-compatible barrel re-export.
 *
 * @module
 * @example
 * ```ts
 * // Import from @/lib/pro-api — still works exactly as before
 * import { loginPro, fetchProSalon } from "@/lib/pro-api";
 * ```
 */
export {
  registerProSessionController,
  refreshSessionWithSingleFlight,
  withApiError,
  fetchProAuthResponse,

  ApiError,
  loginPro,
  registerProOwner,
  requestProOtp,
  verifyProOtp,
  fetchProCurrentUser,
  logoutPro,
  refreshProSession,
  forgotPassword,
  resetProPassword,
  setupProAccount,
  magicLoginPro,
  redeemStaffInviteToken,
  fetchProBookings,
  fetchProBooking,
  acceptProBooking,
  rejectProBooking,
  startProBooking,
  completeProBooking,
  createManualProBooking,
  fetchProClients,
  fetchProClient,
  createClientBenefit,
  fetchProSalon,
  updateProSalon,
  uploadProMedia,
  deleteProMediaAsset,
  fetchProHours,
  updateProHours,
  fetchProBlockedSlots,
  createProBlockedSlot,
  deleteProBlockedSlot,
  fetchProStaff,
  createProStaff,
  updateProStaff,
  deleteProStaff,
  resendProStaffInvite,
  fetchProServices,
  createProService,
  updateProService,
  deleteProService,
  fetchProDashboard,
  fetchProSubscription,
  fetchProSubscriptionFeatures,
  updateProSubscription,
  checkoutProSubscription,
  executeProSubscription,
  cancelProSubscription,
  retainProSubscription,
  fetchProSubscriptionChargeStatus,
  fetchProInvoices,
  downloadProInvoicePdf,
  fetchProPayouts,
  fetchProPayoutSettings,
  updateProPayoutSettings,
  fetchProMerchantPayouts,
  fetchProAnalytics,
  fetchNotificationsUnreadCount,
  fetchNotifications,
  markNotificationRead,
  markAllNotificationsRead,
  createProVoucher,
  fetchProCheckout,
  completeProCheckout,
  fetchPaymentMethods,
  dayOfWeekLabel,
  dayOfWeekOrder,
  getDayLabel
} from "./pro-api/index";
