/**
 * Map of known beauty service names → their category.
 * Used by:
 * 1. ProServicesPage smart combobox (auto-detect category from service name)
 * 2. Seed data validation
 */
export const SERVICE_CATEGORY_MAP: Record<string, string> = {

  // ── Coiffure ─────────────────────────────────────────────────────────
  Brushing: "Coiffure",
  "Brushing + Soin": "Coiffure",
  "Brushing bouclé": "Coiffure",
  "Brushing lissage": "Coiffure",
  "Coupe & Brushing": "Coiffure",
  "Coupe femme": "Coiffure",
  "Coupe homme": "Barbershop",
  "Coupe enfant": "Coiffure",
  "Coupe & Coiffage": "Coiffure",
  Balayage: "Coiffure",
  Coloration: "Coiffure",
  "Coloration naturelle": "Coiffure",
  "Mèches": "Coiffure",
  "Shampoing soin": "Coiffure",
  "Soin capillaire": "Coiffure",
  "Soin kératine": "Coiffure",
  "Soin protéiné": "Coiffure",
  "Soin hydratation capillaire": "Coiffure",
  "Bain d'huile": "Coiffure",
  "Coupe tendance": "Coiffure",
  "Coiffure afro": "Coiffure",
  "Tresses": "Coiffure",
  "Tresses collées": "Coiffure",
  "Tresses passage": "Coiffure",
  "Tissage": "Coiffure",
  "Tissage brésilien": "Coiffure",
  "Tissage indien": "Coiffure",
  "Poses de mèches": "Coiffure",
  "Vanilles": "Coiffure",
  "Lissage brésilien": "Coiffure",
  "Lissage japonais": "Coiffure",
  "Lissage kératine": "Coiffure",
  "Défrisage": "Coiffure",
  "Coupe afro": "Coiffure",
  "Coiffure mariage": "Coiffure",
  "Coiffure soirée": "Coiffure",
  "Chignons": "Coiffure",
  "Permanent": "Coiffure",

  // ── Barbershop ────────────────────────────────────────────────────────
  "Coupe barbe": "Barbershop",
  "Taille barbe": "Barbershop",
  "Coupe + Barbe": "Barbershop",
  "Dégradé homme": "Barbershop",
  "Coupe dégradé": "Barbershop",
  "Rasage traditionnel": "Barbershop",
  "Coupe machine": "Barbershop",
  "Soin barbe": "Barbershop",
  "Coloration barbe": "Barbershop",
  "Soin capillaire homme": "Barbershop",

  // ── Ongles ────────────────────────────────────────────────────────────
  "Pose gel": "Ongles",
  "Pose gel couleur": "Ongles",
  "Remplissage gel": "Ongles",
  "Pose capsule": "Ongles",
  "Semi-permanent": "Ongles",
  "Nail art": "Ongles",
  "Nail art simple": "Ongles",
  "Nail art avancé": "Ongles",
  "Manucure classique": "Ongles",
  "Manucure spa": "Ongles",
  "Pédicure": "Ongles",
  "Pédicure spa": "Ongles",
  "Pose vernis": "Ongles",
  "French manucure": "Ongles",
  "Soin des ongles": "Ongles",
  "Renforcement ongles": "Ongles",
  "Dépose gel": "Ongles",
  "Baby boomer": "Ongles",
  "Cat eye": "Ongles",

  // ── Esthétique ───────────────────────────────────────────────────────
  "Soin visage express": "Esthétique",
  "Soin hydratant": "Soins visage",
  "Soin anti-âge": "Soins visage",
  "Soin éclat": "Soins visage",
  "Soin purifiant": "Soins visage",
  "Soin acides de fruits": "Soins visage",
  "Peeling doux": "Soins visage",
  "Peeling moyen": "Soins visage",
  "Microdermabrasion": "Soins visage",
  "Hydrafacial": "Soins visage",
  "Nettoyage de peau": "Soins visage",
  "Soin contour des yeux": "Soins visage",
  "Masque visage": "Soins visage",
  "Modelage visage": "Soins visage",
  "Soin lumières LED": "Soins visage",

  // ── Soutien-gorge / Corps ────────────────────────────────────────────
  "Soin corps": "Spa & Bien-être",
  "Gommage corps": "Spa & Bien-être",
  "Enveloppement corps": "Spa & Bien-être",
  "Modelage corps": "Spa & Bien-être",
  "Massage relaxant": "Spa & Bien-être",
  "Massage profond": "Spa & Bien-être",
  "Massage aux pierres chaudes": "Spa & Bien-être",
  "Massage suédois": "Spa & Bien-être",
  "Massage thaïlandais": "Spa & Bien-être",
  "Massage drainant": "Spa & Bien-être",
  "Massage amincissant": "Spa & Bien-être",
  "Massage femme enceinte": "Spa & Bien-être",
  "Massage duo": "Spa & Bien-être",
  "Hammam": "Spa & Bien-être",
  "Hammam express": "Spa & Bien-être",
  "Sauna": "Spa & Bien-être",
  "Bain bouillonnant": "Spa & Bien-être",
  "Soin corps enveloppant": "Spa & Bien-être",
  "Rituel bien-être": "Spa & Bien-être",
  "Réflexologie": "Spa & Bien-être",
  "Réflexologie plantaire": "Spa & Bien-être",

  // ── Maquillage ────────────────────────────────────────────────────────
  "Maquillage jour": "Maquillage",
  "Maquillage soirée": "Maquillage",
  "Maquillage mariage": "Maquillage",
  "Maquillage cérémonie": "Maquillage",
  "Maquillage professionnel": "Maquillage",
  "Maquillage nude": "Maquillage",
  "Maquillage glam": "Maquillage",
  "Maquillage afro": "Maquillage",
  "Maquillage yeux": "Maquillage",
  "Maquillage permanent": "Maquillage",
  "Pose faux-cils": "Maquillage",
  "Pose faux-cils volume": "Maquillage",
  "Pose faux-cils réhaussement": "Maquillage",
  "Sourcils microblading": "Maquillage",
  "Sourcils henné": "Maquillage",
  "Épilation sourcils": "Esthétique",
  "Dessin sourcils": "Esthétique",

  // ── Épilation ────────────────────────────────────────────────────────
  "Épilation jambes": "Épilation",
  "Épilation maillot": "Épilation",
  "Épilation aisselles": "Épilation",
  "Épilation bras": "Épilation",
  "Épilation dos": "Épilation",
  "Épilation abdomen": "Épilation",
  "Épilation intégrale": "Épilation",
  "Épilation visage": "Épilation",
  "Épilation lèvre supérieure": "Épilation",
  "Épilation menton": "Épilation",
  "Épilation au fil": "Épilation",
  "Épilation laser": "Épilation",
  "Épilation définitive": "Épilation",
  "Photo-épilation": "Épilation",

  // ── Ongles / Extensions ────────────────────────────────────────────────
  "Extension cils": "Esthétique",
  "Réhaussement cils": "Esthétique",
  "Pose ongles": "Ongles",
};
